In [ ]:
# Write a function so that the columns of the output matrix are powers of the input vector.  
# The order of the powers is determined by the increasing boolean argument. Specifically, 
# when increasing is False, the i-th output column is the input vector raised element-wise   
# to the power of N - i - 1.   
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.   

In [9]:
import numpy as np   # importing numpy package for implementing linear algebra
x = np.array([1, 2, 3, 4, 5])    # 1-D input array
N = 3  # Number of columns in the output. If N is not specified, a square array is returned (N = len(x))

# numpy.vander(x, N=None, increasing=False)  >>>> default values of parameters passed

print('Output Vandermonde Matrix with x :')
# N = len(x) = 5 >>> increasing is False,
# Columns are generated as: first>> x^(N-1), second >> x^(N-2),third >> x^(N-3),fourth >> x^(N-4) and fifth >> x^(N-5)

print(format(np.vander(x)))     
      
print('Output Vandermonde Matrix with x and N :')
# N = 3 >>> increasing is False,
# Columns are generated as: first>> x^(N-1), second >> x^(N-2) and third >> x^(N-3)

print(format(np.vander(x, N)))

print('Output Vandermonde Matrix with x and increasing : ')
# N = len(x) = 5 >>> increasing is True,
# Columns are generated as: first>> x^(N-5), second >> x^(N-4),third >> x^(N-3),fourth >> x^(N-2) and fifth >> x^(N-1)

print(format(np.vander(x, increasing=True)))
              
print('Output Vandermonde Matrix with x, N and increasing : ')
# N = 3 >>> increasing is True,
# Columns are generated as: first>> x^(N-3), second >> x^(N-2) and third >> x^(N-1)

print(format(np.vander(x, N, increasing=True)))


Output Vandermonde Matrix with x :
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Output Vandermonde Matrix with x and N :
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Output Vandermonde Matrix with x and increasing : 
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Output Vandermonde Matrix with x, N and increasing : 
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
